site_name: "Pr1m3d CTF writeups"
site_url: "https://Pr1m3dCTF.github.io/writeups"
site_description: "Pr1m3d CTF Team writeups"
site_author: "Pr1m3d CTF Team"
repo_name: 'Pr1m3dCTF/writeups'
edit_uri: 'blob/master/docs/'
repo_url: 'https://github.com/Pr1m3dCTF/writeups'


theme:
  name: material
  palete:
    primary: green
    accent: blue
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigating.tabs
    - navigating.sections
    - navigating.top
    - search.suggest
    - search.highlight
  favicon: favicon.png
  

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - glightbox
  - search
  - tags:
      title: Pr1m3d CTF writeups
      description: Here we publish some of our writeups for CTF contests
      image: docs/favicon.png
  - social:
      cards: true
      # cards_layout: default



nav:
  - 2023:
    - Cyber Apocalypse 2023: 
      - crypto: 
        - inside the matrix: 2023/cyber-apocalypse-2023/crypto/inside_the_matrix.md
        - multipage recyclings: 2023/cyber-apocalypse-2023/crypto/multipage_recyclings.md
        - perfect synchronization: 2023/cyber-apocalypse-2023/crypto/perfect_synchronization.md
        - small steps: 2023/cyber-apocalypse-2023/crypto/small_steps.md
      - blockchain:
        - navigating the unknown: 2023/cyber-apocalypse-2023/blockchain/navigating_the_unknown.md
        - shooting 101: 2023/cyber-apocalypse-2023/blockchain/shooting_101.md
      - web:
        - passman: 2023/cyber-apocalypse-2023/web/passman.md
      - hardware: 
        - hm74: 2023/cyber-apocalypse-2023/hardware/hm74.md
      - forensics:
        - packet cyclone: 2023/cyber-apocalypse-2023/forensics/packet_cyclone.md
  - 2024:
    - Snapp CTF 2024:
      - crypto: 
        - Cryptos: 2024/Snapp-ctf-2024/crypto/Cryptos.md
        - Bombastic: 2024/Snapp-ctf-2024/crypto/Bombastic.md
        - Blex: 2024/Snapp-ctf-2024/crypto/Blex.md
        - Grail: 2024/Snapp-ctf-2024/crypto/Grail.md
      - pwn:
        - Snapp admin: 2024/Snapp-ctf-2024/pwn/snapp_admin.md
        - Snapp shell: 2024/Snapp-ctf-2024/pwn/snapp_shell.md
      - rev:
        - Visits: 2024/Snapp-ctf-2024/rev/visits.md
        - TurnOB: 2024/Snapp-ctf-2024/rev/turnob.md
        - Blink: 2024/Snapp-ctf-2024/rev/blink.md
      - web:
        - Snapp cat: 2024/Snapp-ctf-2024/web/snapp_cat.md
        - Snapp fal: 2024/Snapp-ctf-2024/web/snapp_fal.md
        - welcome: 2024/Snapp-ctf-2024/web/welcome.md
      - forensics:
        - Snapp Report: 2024/Snapp-ctf-2024/forensics/snapp_report.md
      - osint:
        - Snapp Records: 2024/Snapp-ctf-2024/osint/snapp_records.md
        - Snapp Bounties: 2024/Snapp-ctf-2024/osint/snapp_bounties.md
        - Snapp Customers: 2024/Snapp-ctf-2024/osint/snapp_customers.md
        - Snapp Saving: 2024/Snapp-ctf-2024/osint/snapp_saving.md
    - Cyber Apocalypse 2024:
      - crypto:
        - Permuted: 2024/Cyber-Aplocalypse-2024/crypto/permuted.md
      - blockchain:
        - Lucky Facucet: 2024/Cyber-Aplocalypse-2024/blockchain/luckyfaucet.md
        - Russian Roulette: 2024/Cyber-Aplocalypse-2024/blockchain/russianroulette.md
        - Ledger Heist: 2024/Cyber-Aplocalypse-2024/blockchain/ledgerheist.md
    - Just CTF 2024:
      - blockchain: 2024/JustCTF2024/blockchain/blockchains.md
